language: node_js
sudo: false
node_js:
  - '10'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - dev
    - gh-pages
before_script:
  - npm i
script: ./build/deploy/docs.sh
